#!/usr/bin/env bash
# Installs, Configures and starts a new server

301_REDIRECTION = "\\\tlocation /redirect_me {\n\t\t return 301 https://twitter.com/ataa_nkpa1;\n\t}\n"

apt-get update
apt-get -y upgrade
apt-get -y install nginx

echo "Hello World!" > /usr/share/nginx/html/index.html
sed -i "30i $301_REDIRECTION" /etc/nginx/sites-available/default
service nginx restart
