#!/usr/bin/env bash
# This script displays "Best School", "bad luck" for the 4th iteration and "good luck" for the 8th iteration

index=1

while [ "$index" -lt 10 ]
do
    if [ "$index" -eq 4 ]
    then
        echo "bad luck"
    elif [ "$index" -eq 8 ]
    then
        echo "good luck"
    fi
    echo "Best School"
        (( index++ ))
done
