#!/usr/bin/env bash
# This script displays the numbers 1 through 20, "bad luck from China" for the 4th iteration and "bad luck from Japan" for the 9th iteration and "bad luck from Italy" for the 17th iteration

index=1

while [ "$index" -lt 21 ]
do
    echo "$index"
    case "$index" in
        4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
done
