#!/usr/bin/env bash
# This script displays the contents of the current directory in a list format where only the part of the name after the first dash is displayed

files=$(ls)

for file in files; do
    echo "${file##*-}"
done
