#!/usr/bin/env bash
# This script displays information about the "school" file

if [ -e "school" ]; then
    echo "The file exists"
    if [ -s "school" ]; then
        echo "The file is not empty"
    else
        echo "The file is empty"
    fi
    if [ -f "school" ]; then
        echo "The file is a regular file"
    fi
else
    echo "The file does not exist"
fi
