#!/bin/bash
chmod u+x 1-for_best_school
chmod u+x 2-while_best_school
chmod u+x 3-until_best_school
chmod u+x 4-if_9_say_hi
chmod u+x 5-4_bad_luck_8_is_your_chance
chmod u+x 6-superstitious_numbers
chmod u+x 7-clock
chmod u+x 8-for_ls
chmod u+x 9-to_file_or_not_to_file
chmod u+x 10-fizzbuzz
